### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by liyc-sys** [Zejun-Yang/AniPortrait#108]
Have someone else encountered this problem?

(ani1)  ✘ liyc@ip-172-31-3-70  ~/AniPortrait   main  python -m scripts.app
Traceback (most recent call last):
  File "/home/liyc/anaconda3/envs/ani1/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liyc/anaconda3/envs/ani1/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/liyc/AniPortrait/scripts/app.py", line 43, in <module>
    a2m_model = Audio2MeshModel(audio_infer_config['a2m_model'])
  File "/home/liyc/AniPortrait/src/audio_models/model.py", line 27, in __init__
    self.audio_encoder = Wav2Vec2Model.from_pretrained(model_path, local_files_only=True)
  File "/home/liyc/anaconda3/envs/ani1/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3310, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by Zejun-Yang** [comment]
Seems wav2vec2-base-960h is not complete. Please follow the installation guidance in README (https://github.com/Zejun-Yang/AniPortrait#installation).

**Comment by pikachupichu25** [comment]
I also face the same issue.
```
~/AniPortrait$ python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512 -acc
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/AniPortrait/scripts/audio2vid.py", line 268, in <module>
    main()
  File "/home/ubuntu/AniPortrait/scripts/audio2vid.py", line 66, in main
    a2m_model = Audio2MeshModel(audio_infer_config['a2m_model'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/AniPortrait/src/audio_models/model.py", line 27, in __init__
    self.audio_encoder = Wav2Vec2Model.from_pretrained(model_path, local_files_only=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/AniPortrait/virt/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/AniPortrait/virt/lib/python3.11/site-packages/transformers/modeling_utils.py", line 450, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```


I try to get wav2vec2-base-960h files and still get the same issue.
`git clone https://huggingface.co/facebook/wav2vec2-base-960h`
I think my files are not missing.


```
~/AniPortrait/pretrained_model$ ls wav2vec2-base-960h
README.md                      model.safetensors         special_tokens_map.json  vocab.json
config.json                    preprocessor_config.json  tf_model.h5
feature_extractor_config.json  pytorch_model.bin         tokenizer_config.json
```
