### ISSUE TITLE
pls help to fix this

### ISSUE THREAD

**Issue by xiohulp** [Zejun-Yang/AniPortrait#118]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\AniPortrait\scripts\pose2vid.py", line 210, in <module>
    main()
  File "D:\AniPortrait\scripts\pose2vid.py", line 63, in main
    reference_unet = UNet2DConditionModel.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AniPortrait\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 812, in from_pretrained
    unexpected_keys = load_model_dict_into_meta(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AniPortrait\venv\Lib\site-packages\diffusers\models\modeling_utils.py", line 155, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load ./pretrained_model/stable-diffusion-v1-5 because down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_k.weight expected shape tensor(..., device='meta', size=(320, 1280)), but got torch.Size([320, 768]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

**Comment by G-force78** [comment]
Check you have the same as this here
https://huggingface.co/spaces/ZJYang/AniPortrait_official/tree/main/pretrained_model

**Comment by Zejun-Yang** [comment]
> Check you have the same as this here https://huggingface.co/spaces/ZJYang/AniPortrait_official/tree/main/pretrained_model

Yes, please make sure the pretrained_model file is complete. And you can re-download (stable-diffusion-v1-5)[https://huggingface.co/runwayml/stable-diffusion-v1-5]
