### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by austin20010423** [Zejun-Yang/AniPortrait#136]
Traceback (most recent call last):
  File "/opt/conda/envs/aniportrait/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/aniportrait/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/austin20010423/AniPortrait/scripts/audio2vid.py", line 235, in <module>
    main()
  File "/home/austin20010423/AniPortrait/scripts/audio2vid.py", line 65, in main
    a2m_model = Audio2MeshModel(audio_infer_config['a2m_model'])
  File "/home/austin20010423/AniPortrait/src/audio_models/model.py", line 27, in __init__
    self.audio_encoder = Wav2Vec2Model.from_pretrained(model_path, local_files_only=True)
  File "/opt/conda/envs/aniportrait/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/opt/conda/envs/aniportrait/lib/python3.10/site-packages/transformers/modeling_utils.py", line 450, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by Zejun-Yang** [comment]
model file incomplete
