### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by EvanZouQ** [Zejun-Yang/AniPortrait#148]
Traceback (most recent call last):
  File "D:\DeepLearning\Use\AniPortrait-main\audio2vid.py", line 268, in <module>
    main()
  File "D:\DeepLearning\Use\AniPortrait-main\audio2vid.py", line 264, in main
    ffmpeg.output(stream.video, audio.audio, save_path.replace('_noaudio.mp4', '.mp4'), vcodec='copy', acodec='aac', shortest=None).run()
  File "D:\DeepLearning\Anaconda\install\envs\anip\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\DeepLearning\Anaconda\install\envs\anip\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "D:\DeepLearning\Anaconda\install\envs\anip\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\DeepLearning\Anaconda\install\envs\anip\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Dear authors, I have tried many times with scripts.pose2vid.py/scripts.audio2vid.py, however, this error always occurs. Could you please help me? many thanks.**

**Comment by EvanZouQ** [comment]
Thanks anyway. I have solved this problem via https://phoenixnap.com/kb/ffmpeg-windows.
