### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by invincibledinku** [Zejun-Yang/AniPortrait#160]
(ani-portrait) E:\ANIPORTRAIT\AniPortrait-main\AniPortrait-main>python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\ANIPORTRAIT\AniPortrait-main\AniPortrait-main\scripts\pose2vid.py", line 3, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'

**Comment by ayu2hami** [comment]
You don't have ffmpeg installed.

**Comment by invincibledinku** [comment]
Thanks for the response. I did installed but its not detected somehow, so then I deleted all the files and pulled again. It works 👍🏻
Yahoo Mail: Search, organise, conquer 
 
  On Sun, 19 May 2024 at 4:11, ***@***.***> wrote:   


You don't have ffmpeg installed.
