### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.models.dual_transformer_2d'

### ISSUE THREAD

**Issue by hjcxlp** [Zejun-Yang/AniPortrait#176]
pls advise how to fix this

Traceback (most recent call last):
  File "D:\ComfyUI-A\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-A\custom_nodes\ComfyUI-AniPortrait\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI-A\custom_nodes\ComfyUI-AniPortrait\nodes.py", line 28, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "D:\ComfyUI-A\custom_nodes\ComfyUI-AniPortrait\src\models\unet_2d_condition.py", line 40, in <module>
    from .unet_2d_blocks import (
  File "D:\ComfyUI-A\custom_nodes\ComfyUI-AniPortrait\src\models\unet_2d_blocks.py", line 9, in <module>
    from diffusers.models.dual_transformer_2d import DualTransformer2DModel
ModuleNotFoundError: No module named 'diffusers.models.dual_transformer_2d'

**Comment by G-force78** [comment]
go here to ask
https://github.com/chaojie/ComfyUI-AniPortrait/issues

**Comment by Zejun-Yang** [comment]
Yes, your project is based on ComfyUI. And It seems that the version of diffusers is incorrect.
