### ISSUE TITLE
OSError: Error no file named config.json found in directory ./pretrained_model/stable-diffusion-v1-5.

### ISSUE THREAD

**Issue by nitinmukesh** [Zejun-Yang/AniPortrait#2]
Hello,

I have installed as mentioned in Readme. 

I have not made any changes in the yaml file and trying to run using the default config  and getting this error.
There is no config.json file 
https://huggingface.co/runwayml/stable-diffusion-v1-5

```
(venv) C:\sd\AniPortrait>python -m scripts.pose2vid --config ./configs/prompts/animation.yaml -W 512 -H 512 -L 64
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\sd\AniPortrait\scripts\pose2vid.py", line 199, in <module>
    main()
  File "C:\sd\AniPortrait\scripts\pose2vid.py", line 60, in main
    reference_unet = UNet2DConditionModel.from_pretrained(
  File "C:\sd\AniPortrait\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "C:\sd\AniPortrait\venv\lib\site-packages\diffusers\configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ./pretrained_model/stable-diffusion-v1-5.
```

**Comment by nitinmukesh** [comment]
While downloading the config files from HugginFace it prepend the config file names with folder name.
Renamced the same and it worked.
