### ISSUE TITLE
model loading problem when running pose2vid.py

### ISSUE THREAD

**Issue by NKdryer** [Zejun-Yang/AniPortrait#29]
The following error occurs when loading the pre-trained model：

Traceback (most recent call last):
  File "/ssd-sata1/anaconda3/envs/Ani/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/ssd-sata1/anaconda3/envs/Ani/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ssd-sata1/AniPortrait/scripts/**pose2vid.py**", line 199, in <module>
    main()
  File "/ssd-sata1/AniPortrait/scripts/**pose2vid.py**", line 89, in main
    **torch.load(config.denoising_unet_path, map_location="cpu"),**
  File "/ssd-sata1/anaconda3/envs/Ani/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/ssd-sata1/anaconda3/envs/Ani/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/ssd-sata1/anaconda3/envs/Ani/lib/python3.9/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/ssd-sata1/anaconda3/envs/Ani/lib/python3.9/site-packages/torch/serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
**RuntimeError: PytorchStreamReader failed reading file data/2: invalid header or archive is corrupted**

**Comment by ZeroHackz** [comment]
your anaconda appears to not have a gpu support installed.

**Comment by NKdryer** [comment]
Thanks for your answer, but I think the problem may not be there, because the output from **torch.cuda.is_available()** is True.

**Comment by Zejun-Yang** [comment]
This error usually occurs when the model is damaged. You can check the file size of pre-trained weights from hugging face.

**Comment by NKdryer** [comment]
Thanks so much! I re-downloaded the model on hugging-face and it works.
