### ISSUE TITLE
执行推理报错！

### ISSUE THREAD

**Issue by OpenSorceYCW** [Zejun-Yang/AniPortrait#31]
您好，按照github上给的pretrain_model目录放置好文件后，执行推理时报错，是否需要git lfs 下载所有的文件而不是仅仅下载目录列出的文件呢？ 报错信息时加载stable-diffusion-v1-5 这个目录的模型时报错。报错信息如下：
pretrained_base_model_path:./pretrained_model/stable-diffusion-v1-5
Traceback (most recent call last):
  File "/root/miniconda3/envs/aniport/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 109, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/root/miniconda3/envs/aniport/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/aniport/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/aniport/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/aniport/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/autodl-tmp/AniPortrait/scripts/pose2vid.py", line 202, in <module>
    main()
  File "/root/autodl-tmp/AniPortrait/scripts/pose2vid.py", line 62, in main
    reference_unet = UNet2DConditionModel.from_pretrained(
  File "/root/miniconda3/envs/aniport/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 800, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
  File "/root/miniconda3/envs/aniport/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 116, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.

**Comment by ZeroHackz** [comment]
Execute the commands: 

> `git lfs install`
> `git lfs pull`

and git clone the repository again...

**Comment by OpenSorceYCW** [comment]
重试多遍，克隆本项目后还是报这个问题，换了机器克隆后复制过来也报这个错误。
![image](https://github.com/Zejun-Yang/AniPortrait/assets/22862171/76a3ba4a-24ce-40ed-99ee-a96d4f20499b)

**Comment by OpenSorceYCW** [comment]
是否是git lfs 安装问题，执行git lfs install输出正常，执行git lfs pull 无任何输出，本仓库的git文件如下图：
![image](https://github.com/Zejun-Yang/AniPortrait/assets/22862171/8915c94f-a9e8-42ea-b892-e4311d40df43)

**Comment by OpenSorceYCW** [comment]
pretrain_model的目录结构如下：
![image](https://github.com/Zejun-Yang/AniPortrait/assets/22862171/3de395db-e469-4e4d-aa5c-6863548da5cf)

**Comment by Zejun-Yang** [comment]
可以尝试下载所有依赖预训练模型的完整文件夹。
https://github.com/Zejun-Yang/AniPortrait/blob/195652d07be03762d47d5a43d8a9ca5e7a0fe233/README.md?plain=1#L94

**Comment by OpenSorceYCW** [comment]
感谢博主，已解决！
