### ISSUE TITLE
Mac 下载 decord库报错

### ISSUE THREAD

**Issue by BearSolitarily** [Zejun-Yang/AniPortrait#32]
大家用的都是什么系统啊，Linux还是windows啊，我想在mac上部署运行一下，第一步下载依赖就给我拦下了。看说明说需要降低到python3.8才可以，但是这个项目使用python3.10.😭

**Comment by taozhiyuai** [comment]
> 大家用的都是什么系统啊，Linux还是windows啊，我想在mac上部署运行一下，第一步下载依赖就给我拦下了。看说明说需要降低到python3.8才可以，但是这个项目使用python3.10.😭

用eav-decord

**Comment by taozhiyuai** [comment]
eva-decord

**Comment by BearSolitarily** [comment]
我先去试试eva-decord，感谢回复。

**Comment by taozhiyuai** [comment]
xformers装不上

**Comment by taozhiyuai** [comment]
不知道pip install onnxruntime 和onnxruntime-gpu是否替换的掉

**Comment by BearSolitarily** [comment]
> xformers装不上

大佬，我已经换成windows系统了，我也遇到了xformers的问题，今天晚上准备回去再看看。

**Comment by BearSolitarily** [comment]
> eva 解码

eva-decord在mac确实能用，感谢。

**Comment by Zejun-Yang** [comment]
我们的项目是在Linux系统上研发的。另外可以参考 #37 在windows系统中部署AniPortrait。

**Comment by BearSolitarily** [comment]
> 我们的项目是在Linux系统上研发的。另外可以参考#37在windows系统中部署AniPortrait。

谢谢你，我滴超人。晚点我来回复是否解决问题。

**Comment by taozhiyuai** [comment]
> 我们的项目是在Linux系统上研发的。另外可以参考 #37 在windows系统中部署AniPortrait。

支持下MAC吧~

**Comment by taozhiyuai** [comment]
@BearSolitarily 你在MAC下安装成功没有?我的总是有错,是不是要调整什么

**Comment by taozhiyuai** [comment]
我的错误是这样的.

`(aniportrait) taozhiyu@TAOZHIYUs-MBP aniportrait % python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512
Traceback (most recent call last):
  File "/Users/taozhiyu/miniconda3/envs/aniportrait/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/taozhiyu/miniconda3/envs/aniportrait/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/taozhiyu/Downloads/AniPortrait/scripts/audio2vid.py", line 27, in <module>
    from src.models.model_util import load_models, torch_gc, get_torch_device
  File "/Users/taozhiyu/Downloads/AniPortrait/src/models/model_util.py", line 15, in <module>
    from src.models.unet_2d_condition import UNet2DConditionModel
  File "/Users/taozhiyu/Downloads/AniPortrait/src/models/unet_2d_condition.py", line 18, in <module>
    from diffusers.models.embeddings import (
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (/Users/taozhiyu/miniconda3/envs/aniportrait/lib/python3.10/site-packages/diffusers/models/embeddings.py)
`

**Comment by cxxwode123** [comment]
我也是mac装decord 装不上，不知什么原因

**Comment by FahsaRwatit** [comment]
ImportError: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (/opt/anaconda3/lib/python3.11/site-packages/diffusers/models/embeddings.py)

**Comment by taozhiyuai** [comment]
mac不能跑哦
