### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by afatpig** [Zejun-Yang/AniPortrait#43]
按照ReadMe准备好模型目录后，使用新的conda环境并使用pip -r requirements安装依赖，然后执行python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512，报错：

```shell
# python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512
Some weights of the model checkpoint at ./pretrained_model/wav2vec2-base-960h were not used when initializing Wav2Vec2Model: ['lm_head.bias', 'lm_head.weight']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at ./pretrained_model/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "E:\wsp\ML\AniPortrait\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\wsp\ML\AniPortrait\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\wsp\ML\AniPortrait\scripts\audio2vid.py", line 225, in <module>
    main()
  File "E:\wsp\ML\AniPortrait\scripts\audio2vid.py", line 70, in main
    reference_unet = UNet2DConditionModel.from_pretrained(
  File "E:\wsp\ML\AniPortrait\env\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "E:\wsp\ML\AniPortrait\env\lib\site-packages\diffusers\configuration_utils.py", line 365, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory ./pretrained_model/stable-diffusion-v1-5.
```

**Comment by Zejun-Yang** [comment]
#2 #12
