### ISSUE TITLE
No face detected

### ISSUE THREAD

**Issue by nicefuture2016** [Zejun-Yang/AniPortrait#63]
W:540 H:960的图片提示No face detected,ref_images 必须是正方形 的吗？

```
(venv_name) D:\AniPortrait>python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 540 -H 960
Some weights of the model checkpoint at ./pretrained_model/wav2vec2-base-960h were not used when initializing Wav2Vec2Model: ['lm_head.weight', 'lm_head.bias']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at ./pretrained_model/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:
 ['conv_norm_out.weight, conv_norm_out.bias, conv_out.weight, conv_out.bias']
D:\AniPortrait\venv_name\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1711810808.201596    3792 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "C:\Users\15531\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\15531\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AniPortrait\scripts\audio2vid.py", line 226, in <module>
    main()
  File "D:\AniPortrait\scripts\audio2vid.py", line 143, in main
    assert face_result is not None, "No face detected."
AssertionError: No face detected.
```

**Comment by Zejun-Yang** [comment]
ref_image图片需要手动处理成正方形，另外最好确保较高的人脸占比。更换ref_image也是较好的选择。
