### ISSUE TITLE
I'm a complete newbie....please help 

### ISSUE THREAD

**Issue by LuciusJax** [Zejun-Yang/AniPortrait#64]
(aniportrait) C:\Users\JLafo\Desktop\AniPortrait-for-windows>python -m scripts.audio2vid --config ./configs/prompts/animation_audio.yaml -W 512 -H 512
Some weights of the model checkpoint at ./pretrained_model/wav2vec2-base-960h were not used when initializing Wav2Vec2Model: ['lm_head.bias', 'lm_head.weight']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at ./pretrained_model/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\JLafo\Desktop\AniPortrait-for-windows\scripts\audio2vid.py", line 229, in <module>
    main()
  File "C:\Users\JLafo\Desktop\AniPortrait-for-windows\scripts\audio2vid.py", line 68, in main
    (_,_,unet,_,vae,) = load_models(
                        ^^^^^^^^^^^^
  File "C:\Users\JLafo\Desktop\AniPortrait-for-windows\src\models\model_util.py", line 260, in load_models
    tokenizer, text_encoder, unet, vae = load_diffusers_model(
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JLafo\Desktop\AniPortrait-for-windows\src\models\model_util.py", line 189, in load_diffusers_model
    text_encoder = CLIPTextModel.from_pretrained(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JLafo\anaconda3\envs\aniportrait\Lib\site-packages\transformers\modeling_utils.py", line 2305, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JLafo\anaconda3\envs\aniportrait\Lib\site-packages\transformers\models\clip\configuration_clip.py", line 130, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JLafo\anaconda3\envs\aniportrait\Lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JLafo\anaconda3\envs\aniportrait\Lib\site-packages\transformers\configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\Users\JLafo\anaconda3\envs\aniportrait\Lib\site-packages\transformers\utils\hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: ./pretrained_model/stable-diffusion-v1-5 does not appear to have a file named text_encoder\config.json. Checkout 'https://huggingface.co/./pretrained_model/stable-diffusion-v1-5/None' for available files.

**Comment by Zejun-Yang** [comment]
According to the OSError, the stable-diffusion-v1-5 file is incomplete. You can try to re-download it.

**Comment by LuciusJax** [comment]
I've spent over 8hours, erasing and re-downloading it.

Its just not working 😕

**Comment by Zejun-Yang** [comment]
> I've spent over 8hours, erasing and re-downloading it.
> 
> Its just not working 😕

😂I'm so sorry for that. Maybe you can wait for our hugging face demo page. It's coming soon.
