### ISSUE TITLE
some error in generate_ref_pose

### ISSUE THREAD

**Issue by dabaonidetou** [Zejun-Yang/AniPortrait#84]
when i run generate_ref_pose 

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1712125334.784785    1902 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
W0000 00:00:1712125334.785111    1902 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I0000 00:00:1712125334.822157    1902 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
processing ...:   0%|                                                                                                                              | 0/696 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/test3/AniPortrait/scripts/generate_ref_pose.py", line 92, in <module>
    main()
  File "/usr/src/test3/AniPortrait/scripts/generate_ref_pose.py", line 68, in main
    trans_mat_inv_frame_0 = np.linalg.inv(trans_mat_arr[0])
IndexError: index 0 is out of bounds for axis 0 with size 0
processing ...:   0%|▏                                                                                                                     | 1/696 [00:00<00:28, 24.30it/s]

**Comment by dabaonidetou** [comment]
it also error in vid2pose 

python -m scripts.vid2pose --video_path test.mp4

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1712125095.557950     995 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
W0000 00:00:1712125095.558203     995 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I0000 00:00:1712125095.595351     995 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
  0%|                                                                                                                                              | 0/696 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/src/test3/AniPortrait/scripts/vid2pose.py", line 42, in <module>
    lmks = face_result['lmks'].astype(np.float32)
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/test3/AniPortrait/scripts/vid2pose.py", line 46, in <module>
    pose_img = kps_results[-1]
IndexError: list index out of range

**Comment by Zejun-Yang** [comment]
> when i run generate_ref_pose
> 
> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR I0000 00:00:1712125334.784785 1902 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c W0000 00:00:1712125334.785111 1902 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default. INFO: Created TensorFlow Lite XNNPACK delegate for CPU. I0000 00:00:1712125334.822157 1902 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c processing ...: 0%| | 0/696 [00:00<?, ?it/s]Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/usr/src/test3/AniPortrait/scripts/generate_ref_pose.py", line 92, in main() File "/usr/src/test3/AniPortrait/scripts/generate_ref_pose.py", line 68, in main trans_mat_inv_frame_0 = np.linalg.inv(trans_mat_arr[0]) IndexError: index 0 is out of bounds for axis 0 with size 0 processing ...: 0%|▏ | 1/696 [00:00<00:28, 24.30it/s]

I think it's because no human face can be detected in the first frame of your video. Try to discard the error frames or use another video.

**Comment by Zejun-Yang** [comment]
I think it's because no human face can be detected in the first frame of your video. Try to discard the error frames or use another video.

**Comment by dabaonidetou** [comment]
> I think it's because no human face can be detected in the first frame of your video. Try to discard the error frames or use another video.

我裁剪一下视频试试，最终输出结果如何只输出最终视频呢，我用的是audio2vid，他会输出一个包含原图和面部捕捉的三个画面的视频

**Comment by Zejun-Yang** [comment]
https://github.com/Zejun-Yang/AniPortrait/blob/e4601b8c023f0a9e46a4a6def2f524e9ded6cece/scripts/audio2vid.py#L210

将这一行注释掉即可。

**Comment by dabaonidetou** [comment]
> https://github.com/Zejun-Yang/AniPortrait/blob/e4601b8c023f0a9e46a4a6def2f524e9ded6cece/scripts/audio2vid.py#L210
> 
> 将这一行注释掉即可。

感谢
